package indi.latch.demo.multidatasource.repo.mysql.mapper;

import indi.latch.demo.multidatasource.repo.mysql.domain.UjmTopic;
import indi.latch.demo.multidatasource.repo.mysql.domain.UjmTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UjmTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int countByExample(UjmTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int deleteByExample(UjmTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int insert(UjmTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int insertSelective(UjmTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    List<UjmTopic> selectByExample(UjmTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    UjmTopic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UjmTopic record, @Param("example") UjmTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UjmTopic record, @Param("example") UjmTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UjmTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ujm_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UjmTopic record);
}