package indi.latch.demo.multidatasource.repo.mysql.domain;

import java.util.Date;

public class UjmTaskBasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.topic_code
     *
     * @mbggenerated
     */
    private String topicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.created_by_uid
     *
     * @mbggenerated
     */
    private String createdByUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.updated_by_uid
     *
     * @mbggenerated
     */
    private String updatedByUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ujm_task_basic_info.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.id
     *
     * @return the value of ujm_task_basic_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.id
     *
     * @param id the value for ujm_task_basic_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.name
     *
     * @return the value of ujm_task_basic_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.name
     *
     * @param name the value for ujm_task_basic_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.code
     *
     * @return the value of ujm_task_basic_info.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.code
     *
     * @param code the value for ujm_task_basic_info.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.topic_code
     *
     * @return the value of ujm_task_basic_info.topic_code
     *
     * @mbggenerated
     */
    public String getTopicCode() {
        return topicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.topic_code
     *
     * @param topicCode the value for ujm_task_basic_info.topic_code
     *
     * @mbggenerated
     */
    public void setTopicCode(String topicCode) {
        this.topicCode = topicCode == null ? null : topicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.category
     *
     * @return the value of ujm_task_basic_info.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.category
     *
     * @param category the value for ujm_task_basic_info.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.created_at
     *
     * @return the value of ujm_task_basic_info.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.created_at
     *
     * @param createdAt the value for ujm_task_basic_info.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.updated_at
     *
     * @return the value of ujm_task_basic_info.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.updated_at
     *
     * @param updatedAt the value for ujm_task_basic_info.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.created_by
     *
     * @return the value of ujm_task_basic_info.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.created_by
     *
     * @param createdBy the value for ujm_task_basic_info.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.updated_by
     *
     * @return the value of ujm_task_basic_info.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.updated_by
     *
     * @param updatedBy the value for ujm_task_basic_info.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.created_by_uid
     *
     * @return the value of ujm_task_basic_info.created_by_uid
     *
     * @mbggenerated
     */
    public String getCreatedByUid() {
        return createdByUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.created_by_uid
     *
     * @param createdByUid the value for ujm_task_basic_info.created_by_uid
     *
     * @mbggenerated
     */
    public void setCreatedByUid(String createdByUid) {
        this.createdByUid = createdByUid == null ? null : createdByUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.updated_by_uid
     *
     * @return the value of ujm_task_basic_info.updated_by_uid
     *
     * @mbggenerated
     */
    public String getUpdatedByUid() {
        return updatedByUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.updated_by_uid
     *
     * @param updatedByUid the value for ujm_task_basic_info.updated_by_uid
     *
     * @mbggenerated
     */
    public void setUpdatedByUid(String updatedByUid) {
        this.updatedByUid = updatedByUid == null ? null : updatedByUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ujm_task_basic_info.state
     *
     * @return the value of ujm_task_basic_info.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ujm_task_basic_info.state
     *
     * @param state the value for ujm_task_basic_info.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}